sentences_dict = {
    "sentence_1": ["The", "cat", "sat", "on", "the", "mat."],
    "sentence_2": ["She", "loves", "to", "read", "books."],
    "sentence_3": ["He", "is", "playing", "soccer", "with", "friends."],
    "sentence_4": ["The", "sun", "is", "shining", "brightly."],
    "sentence_5": ["They", "are", "going", "to", "the", "park."],
    "sentence_6": ["I", "enjoy", "cooking", "new", "recipes."],
    "sentence_7": ["The", "dog", "barked", "at", "the", "stranger."],
    "sentence_8": ["We", "are", "learning", "Python", "programming."],
    "sentence_9": ["The", "flowers", "bloom", "in", "the", "spring."],
    "sentence_10": ["She", "walked", "to", "the", "grocery", "store."],
    "sentence_11": ["He", "danced", "to", "the", "music", "at", "the", "party."],
    "sentence_12": ["The", "baby", "is", "sleeping", "in", "the", "crib."],
    "sentence_13": ["My", "favorite", "fruit", "is", "the", "mango."],
    "sentence_14": ["They", "watch", "movies", "every", "Friday", "night."],
    "sentence_15": ["The", "wind", "blew", "through", "the", "trees."],
    "sentence_16": ["He", "drove", "to", "work", "this", "morning."],
    "sentence_17": ["She", "paints", "beautiful", "landscapes", "and", "portraits."],
    "sentence_18": ["The", "children", "played", "in", "the", "playground."],
    "sentence_19": ["They", "love", "to", "travel", "around", "the", "world."],
    "sentence_20": ["I", "like", "to", "watch", "the", "sunset."],
    "sentence_21": ["He", "read", "a", "book", "before", "going", "to", "bed."],
    "sentence_22": ["The", "chocolate", "cake", "tasted", "delicious."],
    "sentence_23": ["She", "enjoys", "hiking", "in", "the", "mountains."],
    "sentence_24": ["The", "stars", "twinkle", "in", "the", "night", "sky."],
    "sentence_25": ["They", "are", "working", "on", "a", "big", "project."],
    "sentence_26": ["He", "likes", "to", "play", "video", "games", "on", "the", "weekends."],
    "sentence_27": ["She", "sings", "beautifully", "in", "the", "choir."],
    "sentence_28": ["The", "computer", "is", "running", "very", "slowly."],
    "sentence_29": ["I", "need", "to", "buy", "some", "groceries."],
    "sentence_30": ["They", "celebrated", "their", "anniversary", "with", "a", "dinner."],
    "sentence_31": ["He", "is", "studying", "hard", "for", "his", "exams."],
    "sentence_32": ["The", "rain", "made", "the", "grass", "green."],
    "sentence_33": ["She", "took", "photos", "during", "her", "vacation."],
    "sentence_34": ["The", "coffee", "is", "brewing", "in", "the", "kitchen."],
    "sentence_35": ["I", "enjoy", "watching", "wildlife", "documentaries."],
    "sentence_36": ["He", "writes", "poems", "in", "his", "free", "time."],
    "sentence_37": ["They", "visited", "the", "museum", "on", "Saturday."],
    "sentence_38": ["The", "baby", "laughed", "at", "the", "funny", "clown."],
    "sentence_39": ["She", "found", "a", "lost", "puppy", "in", "the", "park."],
    "sentence_40": ["The", "waves", "crashed", "against", "the", "shore."],
    "sentence_41": ["He", "enjoys", "running", "in", "the", "early", "morning."],
    "sentence_42": ["They", "had", "a", "picnic", "by", "the", "lake."],
    "sentence_43": ["She", "made", "a", "delicious", "pasta", "dish."],
    "sentence_44": ["The", "teacher", "explained", "the", "lesson", "clearly."],
    "sentence_45": ["He", "built", "a", "sandcastle", "on", "the", "beach."],
    "sentence_46": ["They", "attended", "the", "concert", "last", "night."],
    "sentence_47": ["The", "book", "was", "so", "interesting", "to", "read."],
    "sentence_48": ["She", "practices", "yoga", "to", "stay", "fit."],
    "sentence_49": ["He", "wrote", "a", "letter", "to", "his", "friend."],
    "sentence_50": ["The", "children", "love", "playing", "hide-and-seek."],
}


